### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by XeR** [mxcxvn/newhackbar#4]
Hello,

The previous hackbar had the following shortcuts :
- Load url ( Alt + A )
- Split url ( Alt + S )
- Execute ( Alt + X, Ctrl + Enter )
- INT -1 ( Alt - )
- INT +1 ( Alt + )
- HEX -1 ( Ctrl Alt - )
- HEX +1 ( Ctrl + Alt + )
- MD5 Hash ( Alt + M )
- MySQL CHAR() ( Alt + Y )
- MS SQL Server CHAR() ( Alt + Q )

Is there any plan to add them ?
The alt-x one is particularly useful.

**Comment by jacksonbin** [comment]
Hi,
It was fixed in version 1.0.4
